// Fonte ÚNICA dos textos legais (Termos + Política de Privacidade).
// Consumido pela página PÚBLICA /termos e /privacidade (legal.tsx) e pelas abas
// internas do perfil. Bruno 2026-06-18: a política agora documenta o uso de dados
// da conta Google ("Entrar com Google"), exigência da verificação OAuth do Google.
export type LegalSection = { title: string; content: string };

export const LEGAL_ATUALIZADO = "18/06/2026";

export const TERMOS_TITULO = "Termos e Condicoes de Uso";
export const TERMOS_SUBTITULO = "Plataforma Norte Gestão — CRM WhatsApp para Empresas Brasileiras";

export const TERMOS_SECTIONS: LegalSection[] = [
  { title: "1. Aceitacao dos Termos", content: "Ao acessar ou utilizar a plataforma Norte Gestão (\"Servico\"), voce (\"Usuario\" ou \"Cliente\") concorda com estes Termos e Condicoes de Uso (\"Termos\"). Se voce estiver aceitando estes Termos em nome de uma empresa ou outra entidade legal, declara ter poderes para faze-lo.\n\nCaso nao concorde com qualquer disposicao destes Termos, nao utilize o Servico. O uso continuado apos alteracoes nos Termos implica aceitacao das novas condicoes." },
  { title: "2. Descricao do Servico", content: "O Norte Gestão e uma plataforma SaaS (Software como Servico) de CRM com integracao nativa ao WhatsApp, voltada para pequenas e medias empresas brasileiras. O Servico oferece:\n\n• Gerenciamento de leads, contatos e conversas via WhatsApp\n• Automacoes de mensagens com inteligencia artificial (IA)\n• Funil de vendas (pipeline) e relatorios de desempenho\n• Disparos programados e campanhas de mensagens em massa\n• Integracoes com ferramentas de terceiros (N8n, Zapier, Make, Asaas)\n• Caixa de entrada unificada para equipes\n\nO Servico e fornecido no modelo multi-tenant, onde cada empresa possui um workspace isolado e independente." },
  { title: "3. Cadastro e Conta", content: "Para utilizar o Norte Gestão, e necessario criar uma conta fornecendo informacoes verdadeiras, precisas e atualizadas. Voce pode criar a conta com e-mail e senha ou usando sua conta Google (\"Entrar com Google\"). O Usuario e responsavel por:\n\n• Manter a confidencialidade de suas credenciais de acesso (login e senha)\n• Todas as atividades realizadas sob sua conta\n• Notificar imediatamente a Norte Gestão em caso de acesso nao autorizado\n\nE proibido criar contas com informacoes falsas, compartilhar credenciais entre multiplos usuarios nao autorizados ou criar contas para fins ilicitos." },
  { title: "4. Uso Aceitavel", content: "O Usuario concorda em utilizar o Servico exclusivamente para fins legitimos e em conformidade com a legislacao brasileira vigente, incluindo o Marco Civil da Internet (Lei n 12.965/2014) e o Codigo de Defesa do Consumidor.\n\nSao expressamente proibidos: envio de spam, praticas fraudulentas, acesso nao autorizado a dados de outros Clientes, revenda sem autorizacao, uso de automacoes para assedio ou discriminacao, e coleta de dados sem base legal da LGPD.\n\nA Norte Gestão reserva-se o direito de suspender ou encerrar contas que violem estas regras, sem aviso previo e sem direito a reembolso." },
  { title: "5. Modelo de Cobranca e Pagamento", content: "O Norte Gestão opera com planos de assinatura e/ou cobranca por conexao WhatsApp ativa, conforme o plano contratado. Os valores sao cobrados de forma recorrente pelos meios de pagamento disponiveis na plataforma. A Norte Gestão podera reajustar os valores mediante notificacao previa de 30 dias. Em caso de falha no pagamento, o acesso podera ser suspenso apos 7 dias corridos." },
  { title: "6. Cancelamento e Rescisao", content: "Pelo Cliente: O cancelamento pode ser realizado a qualquer momento. O acesso permanece ativo ate o fim do periodo pago. Nao ha reembolso proporcional.\n\nPela Norte Gestão: Reservamo-nos o direito de rescindir o contrato com aviso previo de 30 dias, salvo em casos de violacao grave.\n\nExportacao de Dados: Apos o cancelamento, o Cliente tera 30 dias para exportar seus dados." },
  { title: "7. Propriedade Intelectual", content: "Todos os direitos sobre a plataforma Norte Gestão sao de titularidade exclusiva da Norte Gestão ou de seus licenciantes. O Cliente recebe uma licenca limitada, nao exclusiva, intransferivel e revogavel. O Cliente mantem todos os direitos sobre os dados inseridos na plataforma." },
  { title: "8. Limitacao de Responsabilidade", content: "O Servico e fornecido \"como esta\" e \"conforme disponivel\". A Norte Gestão nao sera responsavel por perdas decorrentes de interrupcoes causadas por terceiros, conteudo das mensagens dos Clientes, danos indiretos, ou bloqueios impostos pelo WhatsApp/Meta. A responsabilidade total fica limitada ao valor pago no mes do evento danoso." },
  { title: "9. Disponibilidade e Manutencao", content: "A Norte Gestão se compromete a manter disponibilidade minima de 99% ao mes. Manutencoes programadas serao comunicadas com antecedencia minima de 24 horas." },
  { title: "10. Alteracoes nos Termos", content: "A Norte Gestão podera modificar estes Termos a qualquer momento. Alteracoes relevantes serao comunicadas com antecedencia minima de 15 dias." },
  { title: "11. Lei Aplicavel e Foro", content: "Estes Termos sao regidos pelas leis da Republica Federativa do Brasil. Foro da Comarca de Belem, Estado do Para." },
  { title: "12. Contato", content: "E-mail: legal@nortegestao.com.br\nSite: www.nortegestao.com.br" },
];

export const PRIVACIDADE_TITULO = "Politica de Privacidade";
export const PRIVACIDADE_SUBTITULO = "Plataforma Norte Gestão — Conformidade com a LGPD (Lei n 13.709/2018)";

export const PRIVACIDADE_INTRO =
  "A Norte Gestão esta comprometida com a protecao dos seus dados pessoais e com o cumprimento da Lei Geral de Protecao de Dados Pessoais (LGPD — Lei n 13.709/2018). Esta Politica descreve como coletamos, utilizamos, armazenamos, compartilhamos e protegemos suas informacoes.";

export const PRIVACIDADE_SECTIONS: LegalSection[] = [
  { title: "1. Controlador de Dados", content: "O controlador dos dados pessoais tratados nesta Politica e a empresa responsavel pela plataforma Norte Gestão.\n\nE-mail do Encarregado (DPO): privacidade@nortegestao.com.br\nSite: www.nortegestao.com.br\n\nCada empresa (tenant) que utiliza a plataforma atua como controladora independente em relacao aos dados de seus proprios clientes finais, sendo a Norte Gestão operadora nessa relacao." },
  { title: "2. Dados Pessoais Coletados", content: "Dados dos Clientes: Nome completo, e-mail, dados de pagamento, registros de acesso.\n\nDados dos Leads/Contatos: Numero de telefone WhatsApp, nome, historico de mensagens, informacoes adicionais no CRM, gravacoes de audio transcritas via IA.\n\nDados de Uso: Logs de automacoes, campanhas disparadas, interacoes na plataforma." },
  // Bruno 2026-06-18: seção exigida pela verificação OAuth do Google. Documenta os
  // 5 itens pedidos (acesso, uso, compartilhamento, armazenamento, retenção) + a
  // adesão à Google API Services User Data Policy (Limited Use).
  { title: "3. Login com Google (Dados da Conta Google)", content: "Quando voce opta por entrar com sua conta Google (\"Entrar com Google\" / Google Sign-In), tratamos os seguintes dados:\n\n• Dados acessados: nome, endereco de e-mail e foto de perfil da sua conta Google (escopos \"openid\", \"email\" e \"profile\"). NAO acessamos Gmail, Google Drive, Google Agenda nem qualquer outro dado ou servico da sua conta Google.\n\n• Como usamos: exclusivamente para criar e autenticar sua conta na Norte Gestão, identificar voce no momento do login e pre-preencher seu cadastro (nome e e-mail). NAO usamos esses dados para publicidade e NAO os utilizamos para treinar modelos de inteligencia artificial.\n\n• Compartilhamento: NAO compartilhamos os dados obtidos do Google com terceiros. Eles sao usados apenas para o funcionamento do seu acesso a plataforma.\n\n• Armazenamento e protecao: o nome e o e-mail sao armazenados de forma segura em nosso banco de dados; contas criadas via Google recebem uma senha aleatoria inutilizavel (o acesso e sempre pelo Google). Todo o trafego e protegido por HTTPS/TLS e os dados ficam isolados por workspace.\n\n• Retencao e exclusao: mantemos esses dados enquanto a sua conta estiver ativa. Voce pode solicitar a exclusao a qualquer momento pelo e-mail privacidade@nortegestao.com.br; apos o encerramento da conta, os dados sao excluidos conforme a politica de retencao desta secao 7.\n\nO uso das informacoes recebidas das APIs do Google pela Norte Gestão adere a Google API Services User Data Policy, incluindo os requisitos de Uso Limitado (Limited Use)." },
  { title: "4. Finalidade e Base Legal", content: "Execucao de contrato (Art. 7, V): fornecer o Servico, processar pagamentos.\nLegitimo interesse (Art. 7, IX): melhorar a plataforma, prevenir fraudes.\nCumprimento de obrigacao legal (Art. 7, II): exigencias do Marco Civil da Internet.\nConsentimento (Art. 7, I): comunicacoes de marketing." },
  { title: "5. Compartilhamento de Dados", content: "A Norte Gestão nao vende dados pessoais. Compartilhamos apenas com: provedores de infraestrutura, processadores de pagamento, OpenAI (processamento de IA), Meta WhatsApp Cloud API, integracoes ativadas pelo Cliente, e autoridades competentes quando exigido por lei." },
  { title: "6. Seguranca dos Dados", content: "Autenticacao com JWT e senhas com hash seguro (scrypt), isolamento por workspace (multi-tenancy), comunicacoes via HTTPS/TLS, acesso restrito da equipe tecnica, monitoramento continuo." },
  { title: "7. Retencao e Exclusao", content: "Dados de conta ativa: mantidos durante a vigencia da assinatura.\nApos cancelamento: preservados por 30 dias para exportacao.\nLogs de acesso: 6 meses (Marco Civil).\nDados financeiros: 5 anos (legislacao tributaria).\n\nPara solicitar a exclusao dos seus dados, incluindo os obtidos via Login com Google, escreva para privacidade@nortegestao.com.br." },
  { title: "8. Direitos dos Titulares (LGPD)", content: "Confirmacao e acesso, correcao, anonimizacao/bloqueio/eliminacao, portabilidade, eliminacao de dados por consentimento, informacao sobre compartilhamento, revogacao do consentimento, oposicao ao tratamento.\n\nContato: privacidade@nortegestao.com.br — resposta em ate 15 dias uteis." },
  { title: "9. Cookies", content: "A plataforma utiliza cookies essenciais para autenticacao e sessao. Nao utilizamos cookies de rastreamento para fins publicitarios." },
  { title: "10. Transferencia Internacional", content: "Alguns fornecedores (OpenAI, Google) processam dados fora do Brasil, com salvaguardas adequadas conforme Art. 33 da LGPD." },
  { title: "11. Protecao de Menores", content: "O Servico e destinado exclusivamente a pessoas juridicas e maiores de 18 anos." },
  { title: "12. Alteracoes nesta Politica", content: "Alteracoes relevantes serao comunicadas por e-mail ou notificacao na plataforma." },
  { title: "13. Contato e DPO", content: "E-mail DPO: privacidade@nortegestao.com.br\nSuporte: suporte@nortegestao.com.br\nSite: www.nortegestao.com.br\nANPD: www.gov.br/anpd" },
];
